# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2414fcbdbedd4ecaad50edd965c9218a7b9c35046235ad6b54957749df270ff4bd32c90c8203bb4f290ca149abe25a2b67859074c6d19ac7864cd4b549c260d1

test:
  secret_key_base: 86455dc8f0de3cd7b964014924fb9e81fc24a3b82c300bf8af211e4e9768377736da5ec6202c3a4f1a7a219426bc95b2e0f6c1576fb032d4fa0761d3cdc5cf4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
